### ISSUE TITLE
Cursor display

### ISSUE THREAD

**Issue by MoskalykA** [MoskalykA/BuckshotPlusPlus-Examples#2]
Change the cursor display when moving the cursor over the buttons

**Comment by Shubh942** [comment]
@MoskalykA can you please assign me this project?
I have quite an interest in web development and CSS, so it would be a good opportunity for me to showcase the same.

**Comment by MoskalykA** [comment]
Good work ! <3

**Comment by Shubh942** [comment]
Can I write the given program in HTML and CSS

**Comment by MoskalykA** [comment]
No, it should be written in BPP. Here is the file to edit: https://github.com/MoskalykA/BuckshotPlusPlus-Examples/blob/main/Buttons/Pages/Home.bpp

**Comment by Shubh942** [comment]
I am sorry but I don't know anything about bpp files.
I can do this task in HTML and CSS. Can you please explain little about bpp files, I'm not finding anything on internet either.

**Comment by MoskalykA** [comment]
Simply add the keyword "cursor" to the "Over" event of each button like this
![image](https://user-images.githubusercontent.com/100430077/194217971-597944af-34af-42a0-87c5-3bfc2b7bf975.png)
